/**
 * Generates db/seed-hymns.sql from all hymn CSV files.
 * Run locally — no database connection needed.
 *
 * Usage:
 *   node db/generate-seed.js
 *
 * Output:
 *   db/seed-hymns.sql  — paste into phpMyAdmin after running schema.sql
 */

'use strict';
const fs   = require('fs');
const path = require('path');

// ─── Config: point each hymnal code at its CSV file ──────────────────────────

const DOWNLOADS = path.join(process.env.HOME, 'Downloads');

const SOURCES = [
  {
    code:   'CC',
    file:   path.join(DOWNLOADS, 'IBBV hymn index - Copy of Cantor Cristão.csv'),
    format: 'standard',  // cols: number, pt_title, en_title, mp3, gloria, tags
  },
  {
    code:   'SHC',
    file:   path.join(DOWNLOADS, 'IBBV hymn index - Psalmos, Hinos, Canticos.csv'),
    format: 'standard',
  },
  {
    code:   'VM',
    file:   path.join(DOWNLOADS, 'IBBV hymn index - Voz de Melodia.csv'),
    format: 'standard',
  },
  {
    code:   'CDE',
    file:   path.join(DOWNLOADS, 'IBBV hymn index - Corinhos.csv'),
    format: 'corinhos',  // cols: category, empty, pt_title, gloria, en_title
  },
  {
    code:   'HL',
    file:   path.join(DOWNLOADS, 'IBBV hymn index - Hinos de Louvor.csv'),
    format: 'hl',        // cols: number, pt_title, empty, en_title, composer, rating, youtube
  },
];

// ─── CSV parser ───────────────────────────────────────────────────────────────

function parseCSVLine(line) {
  const fields = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (c === '"') {
      inQuotes = !inQuotes;
    } else if (c === ',' && !inQuotes) {
      fields.push(field.trim());
      field = '';
    } else {
      field += c;
    }
  }
  fields.push(field.trim());
  return fields;
}

function escape(str) {
  if (!str) return 'NULL';
  return "'" + str.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
}

// ─── Parsers per format ───────────────────────────────────────────────────────

function parseStandard(lines) {
  const rows = [];
  for (const line of lines) {
    const f = parseCSVLine(line);
    const rawNum = f[0] || '';
    const title  = f[1] || '';
    const enTitle = f[2] || '';

    if (rawNum.toLowerCase().includes('number')) continue; // header
    if (!title) continue;

    const numStr = rawNum.replace(/[^0-9]/g, '');
    if (!numStr) continue;

    rows.push({ number: parseInt(numStr, 10), title, enTitle: enTitle || null });
  }
  return rows;
}

function parseCorinhos(lines) {
  const rows = [];
  const seen = new Set();
  let counter = 1;
  for (const line of lines) {
    const f = parseCSVLine(line);
    // col0: category, col1: empty, col2: pt_title, col3: gloria#, col4: en_title
    const title   = f[2] || '';
    const enTitle = f[4] || '';
    if (!title) continue;
    if (seen.has(title.toLowerCase())) continue;
    seen.add(title.toLowerCase());
    rows.push({ number: counter++, title, enTitle: enTitle || null });
  }
  return rows;
}

function parseHL(lines) {
  const rows = [];
  for (const line of lines) {
    const f = parseCSVLine(line);
    // col0: number, col1: pt_title, col2: empty, col3: en_title
    const rawNum  = f[0] || '';
    const title   = f[1] || '';
    const enTitle = f[3] || '';

    const numStr = rawNum.replace(/[^0-9]/g, '');
    if (!numStr) continue;
    if (!title && !enTitle) continue;

    const number = parseInt(numStr, 10);
    rows.push({
      number,
      title:   title || '(' + enTitle + ')',
      enTitle: enTitle || null,
    });
  }
  return rows;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

const outputPath = path.join(__dirname, 'seed-hymns.sql');
const out = [];

out.push('-- ─── Hymn seed data ─────────────────────────────────────────────────────────');
out.push('-- Generated by db/generate-seed.js — run this in phpMyAdmin after schema.sql');
out.push('-- Safe to re-run: uses INSERT IGNORE so duplicates are skipped.');
out.push('');

let totalRows = 0;

for (const source of SOURCES) {
  if (!fs.existsSync(source.file)) {
    console.warn('WARNING: File not found, skipping ' + source.code + ': ' + source.file);
    continue;
  }

  const raw   = fs.readFileSync(source.file, 'utf8');
  const lines = raw.split('\n').map(l => l.trim()).filter(Boolean);

  let rows;
  if (source.format === 'standard')  rows = parseStandard(lines);
  if (source.format === 'corinhos')  rows = parseCorinhos(lines);
  if (source.format === 'hl')        rows = parseHL(lines);

  out.push('-- ' + source.code + ' (' + rows.length + ' hymns)');
  out.push("SET @hymnal_id = (SELECT id FROM hymnals WHERE code = '" + source.code + "');");
  out.push('INSERT IGNORE INTO hymns (number, title, english_title, hymnal_id) VALUES');

  const valLines = rows.map((r, i) =>
    '  (' + r.number + ', ' + escape(r.title) + ', ' + escape(r.enTitle) + ', @hymnal_id)'
  );
  out.push(valLines.join(',\n') + ';');
  out.push('');

  console.log('  ' + source.code + ': ' + rows.length + ' hymns');
  totalRows += rows.length;
}

fs.writeFileSync(outputPath, out.join('\n'), 'utf8');
console.log('\nWrote ' + totalRows + ' total hymns to db/seed-hymns.sql');
console.log('Run that file in phpMyAdmin after schema.sql.');
